# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- CNAME
- Gemfile
- Gemfile.lock

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

theme: alembic-jekyll-theme

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: HenryAuffahrt # jekyll-seo-tag > Owners twitter username
author: HenryAuffahrt # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Henry Auffahrt # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/HenryAuffahrt
    - https://www.facebook.com/Henry.Auf
#    - https://www.linkedin.com/in/daviddarnes
#    - https://plus.google.com/+DavidDarnes
#    - https://github.com/daviddarnes

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Berlin # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "My thoughts and ideas" # The post list page content
    feature_text: |
      Welcome to the blog
    feature_image: "https://unsplash.it/1300/400?image=1067"

# 6. Jekyll collections settings
defaults:
  -
    values:
      image: "/assets/default-social-image.png" # Default image for sharing
#    scope:
#        path: "/assets/img"
#      values:
#        image: true

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: de-DE # Set the site language
title: "Henry" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "Henrys Blog berichtet von dem kunterbunten Leben eines Webentwicklers, Auto- und Motorradliebhabers, Hobby-DJs und Sportbegeisterten" # Site description and default description, also used in jekyll-seo-tag
url: "https://henry.auffie.de" # Site url, also used in jekyll-seo-tag
repo: "https://github.com/Henry31/henry31.github.io"
email: "henry@auffie.de"
# disqus: "" # Blog post comments, uncomment the option and set the site ID from your Disqus account
avatarurl: "https://www.gravatar.com/avatar/834da024eb85d2eb3886e84105af0884" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub

# 8. Site navigation
navigation_header:
  Home: /
  Elements: /elements/
  Blog: /blog/
  Categories: /categories/
  Search: /search/
 #Fork Alembic: https://github.com/daviddarnes/alembic

navigation_footer:
  Created by Henry Auffahrt: http://henry.auffie.de

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/HenryAuffahrt
  #LinkedIn: https://www.linkedin.com/in/daviddarnes
  #Google+: https://plus.google.com/+DavidDarnes
  GitHub: https://github.com/Henry31
  link: http://henry.auffie.de
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#1DA1F2"
  facebook: "#3B5998"
  Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  # LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  # Email: ""

#bf0505